### ISSUE TITLE
Debug Working Very Very Slow

### ISSUE THREAD

**Issue by MindShow** [sipeed/platform-gd32v#5]
When use PlatformIO，
Debug Working Very Very Slow,
but the same hardware work very well with eclipseMCU IDE
How to solve this problem

[https://youtu.be/Jscnaj9HSek](url)

**Comment by ivankravets** [comment]
2 reason:

1) Please use `PIO Debug (Skip PRE-Debug)` profile, near green start debug button
2) Debugging is slow because you expanded generic and peripheral register views. There is a bug in toolchain which returns hundresssss unknown registers. Each time when you do a step, we update these values in views.

Could you try to collapse register views and restart VSCode and try debugging again? It should MUCH faster than Eclipse.

**Comment by MindShow** [comment]
thanks，
collapse register views -> collapse peripheral ->restart vscode -> start debug -> enjoy it

**Comment by ivankravets** [comment]
@btx000 @Zepan Is this valid SVD file for GD32V https://github.com/sipeed/platform-gd32v/blob/master/misc/svd/GD32VF103.svd?
I see it was renamed from ARM M3. Thanks!

**Comment by bitsk** [comment]
Yes, they are identical at the register level.
